setGeneric("MAService", function(object, sentence, ...)
    standardGeneric("MAService"))
setGeneric("DAService", function(object, sentence)
    standardGeneric("DAService"))
setGeneric("Keyphrase", function(object, sentence)
    standardGeneric("Keyphrase"))
setGeneric("toDataFrame", function(object)
    standardGeneric("toDataFrame"))
setGeneric("post", function(object, url, params="list")
    standardGeneric("post"))
